import {
  MODEL_KEYS,
  MODEL_LABELS,
  METHODS,
  METHOD_LABELS,
  METHOD_SUPPORTED,
  type Method,
  type ModelKey,
} from "../config";
import { useExplorerStore } from "../stores/useExplorerStore";
import type {
  CamEntry,
  LimeEntry,
  RolloutEntry,
  Sample,
} from "../types";
import { HeatmapOverlay } from "./HeatmapOverlay";
import { Section, Card } from "./Section";

type MethodDescription = {
  body: string;
  source: { label: string; href: string };
};

const METHOD_DESCRIPTIONS: Record<Method, MethodDescription> = {
  gradcam: {
    body: "Grad-CAM weights each feature map of the last convolutional (or attention) layer by the gradient of the predicted class score with respect to that map, then upsamples the result to image resolution. Bright regions are pixels whose presence would most increase the predicted class. It's fast and shows where the model is looking, but the resolution is limited by the chosen layer's feature-map size, so the highlights are coarse. ViT Grad-CAM tends to look flatter than CNN Grad-CAM because every patch token attends to every other patch, so the gradient signal spreads more uniformly.",
    source: {
      label: "Grad-CAM: Visual Explanations from Deep Networks via Gradient-Based Localization — Selvaraju et al., 2017 (arXiv:1610.02391)",
      href: "https://arxiv.org/abs/1610.02391",
    },
  },
  scorecam: {
    body: "Score-CAM drops the gradient. For each feature map at the target layer it builds a soft mask, multiplies it against the input, runs the masked image through the model, and weights the map by the resulting class score. Slower than Grad-CAM (hundreds of forward passes per image) but the saliency comes from changes in the prediction rather than a gradient signal, which makes it less sensitive to ReLU saturation and noisy gradients.",
    source: {
      label: "Score-CAM: Score-Weighted Visual Explanations for Convolutional Neural Networks — Wang et al., 2020 (arXiv:1910.01279)",
      href: "https://arxiv.org/abs/1910.01279",
    },
  },
  saliency: {
    body: "Vanilla saliency: take the gradient of the predicted class score with respect to each input pixel and visualize its magnitude. It's pixel-level and noisy, with a tendency to scatter signal across edges, but it shows the raw input-space sensitivity without smoothing or aggregation.",
    source: {
      label: "Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps — Simonyan et al., 2014 (arXiv:1312.6034)",
      href: "https://arxiv.org/abs/1312.6034",
    },
  },
  lime: {
    body: "LIME explains a single prediction by perturbing it. The image is broken into superpixels (here ~50 SLIC segments), thousands of variants are generated by masking random subsets, and a sparse linear model is fit to the perturbations' predictions. The result is which superpixels push the prediction up (positive) or down (negative). It's a model-agnostic, locally-faithful explanation, but the segmentation choice and number of samples both affect what you see.",
    source: {
      label: "“Why Should I Trust You?”: Explaining the Predictions of Any Classifier — Ribeiro et al., 2016 (arXiv:1602.04938)",
      href: "https://arxiv.org/abs/1602.04938",
    },
  },
  rollout: {
    body: "Attention Rollout is ViT-specific. At each transformer block, the per-head attention matrices are averaged, the residual connection is added as an identity, and the result is row-normalized. The matrices from all blocks are then multiplied together, and the CLS token's row of the product tells you how much each input patch contributes to the final classification. It's gradient-free and tends to give crisper, more localized maps than Grad-CAM on ViTs.",
    source: {
      label: "Quantifying Attention Flow in Transformers — Abnar & Zuidema, 2020 (arXiv:2005.00928)",
      href: "https://arxiv.org/abs/2005.00928",
    },
  },
};

type Props = {
  classes: string[];
  samples: Sample[];
  cams: Record<ModelKey, CamEntry[]>;
  lime: Record<ModelKey, LimeEntry[]>;
  rollout: Partial<Record<ModelKey, RolloutEntry[]>>;
};

function ProbBars({
  probs,
  classes,
  trueClass,
}: {
  probs: number[];
  classes: string[];
  trueClass: string;
}) {
  const indexed = probs.map((p, i) => ({ p, label: classes[i] }));
  indexed.sort((a, b) => b.p - a.p);
  const top = indexed.slice(0, 3);
  return (
    <div className="flex flex-col gap-1">
      {top.map((r, i) => (
        <div key={r.label} className="flex items-center gap-2">
          <span
            className={
              "text-xs truncate w-20 text-gray-600 dark:text-zinc-400 " +
              (r.label === trueClass ? "font-medium" : "")
            }
            title={r.label}
          >
            {r.label}
          </span>
          <div className="flex-1 h-1 bg-gray-100 dark:bg-zinc-800 rounded-full overflow-hidden">
            <div
              className={
                i === 0
                  ? "h-full bg-blue-600 dark:bg-blue-500"
                  : "h-full bg-gray-400 dark:bg-zinc-500"
              }
              style={{ width: `${r.p * 100}%` }}
            />
          </div>
          <span className="text-xs text-gray-500 dark:text-zinc-500 w-9 text-right tabular-nums">
            {(r.p * 100).toFixed(0)}%
          </span>
        </div>
      ))}
    </div>
  );
}

function findSample(samples: Sample[], id: string | null) {
  return id ? samples.find((s) => s.id === id) ?? null : null;
}

function findCam(entries: CamEntry[] | undefined, id: string | null) {
  return id && entries ? entries.find((e) => e.id === id) ?? null : null;
}

function findLime(entries: LimeEntry[] | undefined, id: string | null) {
  return id && entries ? entries.find((e) => e.id === id) ?? null : null;
}

function findRollout(
  entries: RolloutEntry[] | undefined,
  id: string | null,
) {
  return id && entries ? entries.find((e) => e.id === id) ?? null : null;
}

function gridFor(
  method: Method,
  cam: CamEntry | null,
  lime: LimeEntry | null,
  ro: RolloutEntry | null,
): number[][] | undefined {
  if (method === "lime") return lime?.heatmap;
  if (method === "rollout") return ro?.rollout;
  return cam?.maps[method as Exclude<Method, "lime" | "rollout">];
}

export function InterpretabilityTabs({
  classes,
  samples,
  cams,
  lime,
  rollout,
}: Props) {
  const method = useExplorerStore((s) => s.method);
  const setMethod = useExplorerStore((s) => s.setMethod);
  const selectedId = useExplorerStore((s) => s.selectedId);
  const setSelectedId = useExplorerStore((s) => s.setSelectedId);

  const sample = findSample(samples, selectedId);

  return (
    <Section
      id="per-image"
      number="02"
      title="Per-image interpretability"
      blurb="Pick an image and a method to see where each model looks when it makes its prediction. A green border means the model classified the image correctly, red means it missed."
    >
      <div className="flex justify-end">
        <div className="flex gap-1 bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-md p-1">
          {METHODS.map((m) => (
            <button
              key={m}
              type="button"
              onClick={() => setMethod(m)}
              className={
                "px-3 py-1 text-xs rounded-sm transition cursor-pointer " +
                (method === m
                  ? "bg-blue-600 text-white dark:bg-blue-500"
                  : "text-gray-600 dark:text-zinc-400 hover:text-gray-900 dark:hover:text-zinc-100")
              }
            >
              {METHOD_LABELS[m]}
            </button>
          ))}
        </div>
      </div>

      <Card>
      {!sample ? (
        <p className="text-sm text-gray-500 dark:text-zinc-500">
          Pick an image below to see interpretability output.
        </p>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">
          {MODEL_KEYS.map((m) => {
            const cam = findCam(cams[m], sample.id);
            const li = findLime(lime[m], sample.id);
            const ro = findRollout(rollout[m], sample.id);
            const supported = (
              METHOD_SUPPORTED[method] as readonly ModelKey[]
            ).includes(m);
            const grid = supported ? gridFor(method, cam, li, ro) : undefined;
            const correct =
              cam ? cam.pred_class === cam.true_class : undefined;
            const borderClass =
              correct === true
                ? "border-green-500 dark:border-green-500"
                : correct === false
                  ? "border-red-500 dark:border-red-500"
                  : "border-gray-300 dark:border-zinc-700";
            return (
              <div key={m} className="flex flex-col gap-2">
                <div className="text-xs uppercase tracking-wider text-gray-500 dark:text-zinc-500 font-mono">
                  {MODEL_LABELS[m]}
                </div>
                <div
                  className={
                    "relative rounded-md border-2 overflow-hidden " +
                    borderClass
                  }
                >
                  <HeatmapOverlay
                    imageSrc={`/samples/${sample.file}`}
                    grid={grid}
                    signed={method === "lime"}
                  />
                  {!supported && (
                    <div className="absolute inset-0 flex items-center justify-center bg-white/60 dark:bg-zinc-900/60 backdrop-blur-[2px]">
                      <span className="text-xs text-gray-700 dark:text-zinc-300 px-2 py-1 rounded bg-white/80 dark:bg-zinc-900/80 border border-gray-200 dark:border-zinc-700">
                        not applicable to {MODEL_LABELS[m]}
                      </span>
                    </div>
                  )}
                </div>
                {cam && (
                  <ProbBars
                    probs={cam.probs}
                    classes={classes}
                    trueClass={cam.true_class}
                  />
                )}
              </div>
            );
          })}
        </div>
      )}

      {sample && (
        <div className="mt-3 text-xs text-gray-500 dark:text-zinc-500">
          True class:{" "}
          <span className="text-gray-700 dark:text-zinc-300">{sample.class}</span>
        </div>
      )}
      <div className="mt-4">
        <p className="text-sm text-gray-600 dark:text-zinc-400 leading-relaxed">
          <span className="text-gray-900 dark:text-zinc-100 font-medium">
            {METHOD_LABELS[method]}.
          </span>{" "}
          {METHOD_DESCRIPTIONS[method].body}
        </p>
        <p className="mt-2 text-xs text-gray-500 dark:text-zinc-500">
          Source:{" "}
          <a
            href={METHOD_DESCRIPTIONS[method].source.href}
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 dark:text-zinc-400 underline"
          >
            {METHOD_DESCRIPTIONS[method].source.label}
          </a>
        </p>
      </div>

      <div className="mt-5 pt-4 border-t border-gray-200 dark:border-zinc-800">
        <div className="text-xs uppercase tracking-wider text-gray-500 dark:text-zinc-500 font-mono mb-2">
          ImageNette samples
        </div>
        <div className="grid grid-cols-5 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 gap-2 max-h-72 overflow-y-auto">
          {samples.map((s) => {
            const active = s.id === selectedId;
            return (
              <button
                type="button"
                key={s.id}
                onClick={() => setSelectedId(s.id)}
                title={s.class}
                className={
                  "relative aspect-square overflow-hidden rounded-sm border transition cursor-pointer " +
                  (active
                    ? "border-blue-600 ring-2 ring-blue-600 dark:border-blue-400 dark:ring-blue-400"
                    : "border-gray-200 dark:border-zinc-700 hover:border-gray-400 dark:hover:border-zinc-500")
                }
              >
                <img
                  src={`/samples/${s.file}`}
                  alt={s.class}
                  className="w-full h-full object-cover"
                  loading="lazy"
                />
              </button>
            );
          })}
        </div>
      </div>
      </Card>
    </Section>
  );
}
